# Generated by Django 5.2.5 on 2025-08-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalClinica',
            fields=[
                ('id_hc', models.AutoField(primary_key=True, serialize=False)),
                ('rnc', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('especializacion', models.CharField(max_length=50)),
                ('firma_digital', models.BinaryField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='srrm_app.hospitalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=13, null=True)),
                ('seguro', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='srrm_app.hospitalclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='srrm_app.medico')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('hora_descarga', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='srrm_app.hospitalclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='srrm_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='srrm_app.paciente')),
            ],
        ),
    ]
