# Generated by Django 5.2.5 on 2025-08-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='hospitales',
            field=models.ManyToManyField(related_name='medicos', to='srrm_app.hospitalclinica', verbose_name='Hospitales/Clínicas donde trabaja'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hospitales',
            field=models.ManyToManyField(related_name='pacientes_hospital', to='srrm_app.hospitalclinica', verbose_name='Hospitales/Clínicas donde está registrado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicos',
            field=models.ManyToManyField(related_name='pacientes', to='srrm_app.medico', verbose_name='Médicos que atienden al paciente'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_emitidas', to='srrm_app.medico'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_recibidas', to='srrm_app.paciente'),
        ),
    ]
